### ISSUE TITLE
kTLS doesn't handle TLS control messages

### ISSUE THREAD

**Issue by Skepfyr** [hapsoc/ktls#18]
https://github.com/hapsoc/ktls/blob/89d9d4287d99aefb431def237c6a33a52dd221e7/src/lib.rs#L190-L196

I believe the "(and key updates, etc.)" in this line is incorrect, that you have to handle TLS control messages (like rekeys) in the application: https://www.kernel.org/doc/html/latest/networking/tls.html#receiving-tls-control-messages.

Note I don't know this for certain only by reading the kernel docs, I just happened to spot this doc while skimming this codebase.

**Comment by NobodyXu** [comment]
I googled "linux ktls rekey" and the first few results are all from FreeBSD and says that "As a result, applications must disable rekeying when using ktls".

Obviously kTLS in FreeBSD cannot handle rekey, I guess maybe linux kTLS also cannot handle rekey.

**Comment by NobodyXu** [comment]
@fasterthanlime since this issue has been stale for quite some time.
