### ISSUE TITLE
Odd, new, IO errors when using kTLS

### ISSUE THREAD

**Issue by jeromegn** [hapsoc/ktls#20]
I believe these are caused by constraints in the kernel's TLS implementation. We started seeing:
- `Message too long (os error 90)`
- `Invalid argument (os error 22)`

They appeared seemingly out of nowhere while proxying data. Often as part of `hyper` request / response bodies polling.

There might be limitations with the size of buffers it can handle and I expect the implementation changed a lot over time with newer kernel versions.

We could not reproduce in a testing environment, but it did start to happen frequently in production for the few minutes this was deployed in a few regions.

Reverting to using userspace TLS crypto (`rustls`) fixed the issue.

**Comment by fasterthanlime** [comment]
I believe limiting writes to `0 < buf_size < (1 << 14)` might get rid of either or both of these - but if I'm right this should be easy to reproduce.

**Comment by jeromegn** [comment]
With my kernel 6.2.3, I was able to reproduce the issue with a large `CLIENT_PAYLOAD` and truncating it to `(32 * 1024) - 44`. I started getting `Message too long` errors with that value.

Starting at `(32 * 1024) - 45` and less, I didn't get the error.

That's an odd value.

I couldn't reproduce with a large `SERVER_PAYLOAD`, but I only tested up to 128KB.

**Comment by jeromegn** [comment]
I added logging to the `poll_read` when there's data to drain and the plot thickens:

```
  2023-03-25T15:04:55.743447Z DEBUG integration_test: Reading data
    at tests/integration_test.rs:133
    in integration_test::server

  2023-03-25T15:04:55.743453Z DEBUG ktls::ktls_stream: draining from index 0, len: 16384
    at src/ktls_stream.rs:73
    in integration_test::server

  2023-03-25T15:04:55.743591Z DEBUG rustls::client::tls13: Ticket saved
    at /home/jerome/.cargo/registry/src/github.com-1ecc6299db9ec823/rustls-0.20.8/src/client/tls13.rs:1050
```

It appears to be draining before the `rustls::client::tls13::ExpectTraffic::handle_new_ticket_tls13` call. Maybe that's the issue?

**Comment by jeromegn** [comment]
Yeah ok, I think this has everything to do with: was there anything to drain? aka: "rustls read too much."

For example, in my testing, it all works fine if the `secrets.rx`'s `seq` is `0`. But when my payload is too big, the `seq` is `1`.

I guess this could be caused by ktls missing some bytes and therefore not knowing about the start of the TLS record? In other words:
- rustls reads a bunch of data
- convert tokio-rustls `TlsStream` to a `KtlsStream`:
  - drain the `TlsStream` by `poll_read`-ing once, at most 16KB (I tried a bigger buffer, but it always ends up reading 16KB)
  - store that buffer in the `KtlsStream`'s `drained`
- `KtlsStream::poll_read` goes through the drained data first
- next `poll_read` breaks.

As an experiment, I looped the drain `poll_read` twice to get >= 32KB of data and that fixed it. Admittedly none of that went through the kernel since it was read in userspace, but it sounds like `ktls` needs a way to fully drain the connection's read bytes.

Does `rustls` read more than 16KB? Seems like it did the handshake and then read everything I sent it even if it was over the maximum size for a TLS record (16KB).

I'm probably confusing a lot of things together here. I really want this to work so I thought I'd try and fix it, but I might've hit a wall.

**Comment by fasterthanlime** [comment]
I mean that seems like a reasonable explanation, and looping to make sure we fully drain from rustls seems like a reasonable fix? (Until/unless we can get a better interface from rustls)

**Comment by jeromegn** [comment]
I'm mostly concerned about reading from the `tokio_rustls::TlsStream` needlessly if I loop `poll_read` when draining. I'd like to be able to switch to kernel offload as soon as possible after the initial handshake.

If I `poll_read` in a loop on my server connection and the client is happily sending data, then it won't end and I'll be "stuck" in userspace.

You hinted at a solution on Discord, but I'm not sure I understand it :) I'm happy to do the work with a bit more guidance.
