### ISSUE TITLE
Can't compile project with KTLS crate

### ISSUE THREAD

**Issue by nikaaboda** [hapsoc/ktls#23]
Created brand new project and added `ktls = 2.0.0` as a dependency. 
I believe, there is mismatched types in ffi.rs:
```
/ktls-2.0.0/src/ffi.rs:209:27
    |
209 |                 cmsg_len: memoffset::offset_of!(Self, data) + N,
    |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `u32`, found `usize`
    
    error: could not compile `ktls` due to previous error
```
I'd try to fix it, but this is my first touch with rust.

**Comment by fasterthanlime** [comment]
Can you post the details of your system? What’s your Linux distribution and kernel version?

**Comment by fasterthanlime** [comment]
<img width="717" alt="image" src="https://user-images.githubusercontent.com/7998310/235601415-e6581148-dad5-4096-a00e-f15fc46caac9.png">

A hello world with ktls=2.0.0 as a dependency builds fine on 64-bit Ubuntu 22.04, Linux 5.12.2 — I'm curious what's different about your setup.

**Comment by nikaaboda** [comment]
I was testing it on mac. My bad, didn't realise I needed Linux distribution.

**Comment by nikaaboda** [comment]
Would be nice. I'm trying to use your crate in my project (for bachelor thesis). Once I'm done with that, I'd like try to improve small things like this for ktls (if you have something else in mind too).
