### ISSUE TITLE
Handle lack of `tls` kernel module more gracefully

### ISSUE THREAD

**Issue by fasterthanlime** [hapsoc/ktls#7]
Right now it fails with:

```
thread 'ktls_server_rustls_client_tls_1_3_chacha20_poly1305' panicked at 'called `Result::unwrap()` on an `Err` value: UlpError(TlsStream { io: PollEvented { io: Some(TcpStream { addr: [::1]:44593, peer: [::1]:55546, fd: 11 }) }, session: ServerConnection, state: Stream }, Os { code: 2, kind: NotFound, message: "No such file or directory" })', tests/integration_test.rs:90:67
```

We could probably have a custom error when we get a "Not Found" when setting up ULP.

**Comment by fasterthanlime** [comment]
I've just found out a bit more about how kernel modules and I _think_ we can do something like check if `/sys/module/tls/initstate` 1) exists 2) contains the word 'live'. And if not we can just bail out.

**Comment by NobodyXu** [comment]
What if the process runs in a container/sandbox environment where `/sys/module/tls` isn't mapped or if ktls is statically linked?

I don't think probing `/sys/module` is generally a good idea though, as an end user I sure don't want random program to poke at it.

**Comment by fasterthanlime** [comment]
> What if the process runs in a container/sandbox environment where `/sys/module/tls` isn't mapped or if ktls is statically linked?

Yeah, that raises several important questions: re TLS being built-in (`=y`) rather than a module (`=m`), I'm about to find out via fly machines how that actually behaves.

Re containers, I actually have no idea if the syscall would even be let through, it'll be interesting to find out, too.

**Comment by NobodyXu** [comment]
> Yeah, that raises several important questions: re TLS being built-in (=y) rather than a module (=m), I'm about to find out via fly machines how that actually behaves.

IMO if only there is syscall to test this.

Maybe we can [create a ktls conn](https://docs.kernel.org/networking/tls.html#creating-a-tls-connection) just to test whether it is available and then throw it away at startup and using something like `OnceCell` or `AtomicBool` to cache the result?

> Re containers, I actually have no idea if the syscall would even be let through, it'll be interesting to find out, too.

It might be fine for docker since it indeeds mount `/sys`, but it might not be able to access `/sys/module` unless the container is privileged.

**Comment by fasterthanlime** [comment]
> Maybe we can [create a ktls conn](https://docs.kernel.org/networking/tls.html#creating-a-tls-connection) just to test whether it is available and then throw it away at startup and using something like `OnceCell` or `AtomicBool` to cache the result?

This is what I ended up doing:

https://github.com/hapsoc/ktls/blob/3f0e183576f5a0e6dc7d499ac50acd0b3a2766db/src/lib.rs#L34-L103

**Comment by NobodyXu** [comment]
@fasterthanlime IMO perhas it's better for CompatibleCiphers::new to be an async function to avoid spawning an extra thread?

I can submit a PR for this,

**Comment by fasterthanlime** [comment]
> @fasterthanlime IMO perhas it's better for CompatibleCiphers::new to be an async function to avoid spawning an extra thread?

The intent is to use this at application startup, so it might be done even before the tokio runtime starts, I don't think it _needs_ to be async (but it could be).

**Comment by NobodyXu** [comment]
> > @fasterthanlime IMO perhas it's better for CompatibleCiphers::new to be an async function to avoid spawning an extra thread?
> 
> The intent is to use this at application startup, so it might be done even before the tokio runtime starts, I don't think it _needs_ to be async (but it could be).

I understand that, I just simply don't like the `thread::spawn`ing part TBH.
But that's just my own opinion, feel free to ignore that if you think it's ok.

**Comment by fasterthanlime** [comment]
> I just simply don't like the `thread::spawn`ing part TBH.

Mhh that's true, an async version of this code wouldn't have to spawn a thread - feel free to open a PR for that if you want to!

**Comment by NobodyXu** [comment]
I've opened PR #11 for this.
